# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 1

  - name: Introduction
    weight: 2
  - parent: Introduction
    name: About
    url: /about#about
    weight: 50
  - parent: Introduction
    name: Experience
    url: /about#experience
    weight: 50


  - name: Posts
    url: /posts
    weight: 3
  - parent: Posts
    name: All Posts
    url: /posts
    weight: 50
  - parent: Posts
    name: Soft Skills
    url: /softskills
    weight: 50
  - parent: Posts
    name: Hard Skills    
    url: /hardskills
    weight: 50  

  - name: Leisure
    url: /experience
    weight: 5
  - parent: Leisure
    name: Hobby
    url: /experience/hobby
    weight: 50
  - parent: Leisure
    name: Book
    url: /experience/book
    weight: 50

  - name: Projects
    url: projects/
    weight: 4
  - parent: Projects
    name: Web
    url: /web
    weight: 50
  - parent: Projects
    name: CS
    url: /cs
    weight: 50

  - name: Contact
    url: contact/
    weight: 20
  
